export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/register'
export const MAP_ROUTE = '/'
export const INVENTORY_ROUTE = '/inventory'
export const PROFILE_ROUTE = '/profile'
export const BANK_ROUTE = '/bank'
export const ADMIN_ROUTE = '/adminPanel'