export const LOGIN_ROUTE = '/'
export const REG_ROUTE = '/register'
export const MAP_ROUTE = '/map'
export const INVENTORY_ROUTE = '/inventory'
export const PROFILE_ROUTE = '/profile'
export const BANK_ROUTE = '/bank'
export const ADMIN_ROUTE = '/adminPanel'
export const HOMEPAGE_ROUTE = '/home'